name: Deploy TernakPro_App to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan workflow di mesin Ubuntu

    steps:
    # Langkah 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2  # Mengambil kode dari repositori

    # Langkah 2: Set up PHP untuk Laravel
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Sesuaikan dengan versi PHP yang digunakan di server Anda
        extensions: mbstring, bcmath, pdo, pdo_mysql  # Tambahkan ekstensi yang diperlukan oleh Laravel

    # Langkah 3: Install Composer dependencies
    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction --prefer-dist

    # Langkah 4: Setup SSH key untuk akses ke server
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Menggunakan SSH private key dari GitHub Secrets

    # Langkah 5: Sync file Laravel dengan server menggunakan rsync
    - name: Sync files with server
      run: |
        rsync -avz --delete ./ ternakpro.id@ssh.gb.stackcp.com:/home/sites/2b/5/535431543a/public_html/ternakpro_app  # Sesuaikan path di server Anda

    # Langkah 6: Set permissions di server untuk folder Laravel
    - name: Set permissions
      run: |
        ssh ternakpro.id@ssh.gb.stackcp.com "cd /home/sites/2b/5/535431543a/public_html/ternakpro_app && sudo chmod -R 775 storage bootstrap/cache"

    # Langkah 7: Menjalankan migrasi Laravel
    - name: Run Laravel migrations
      run: |
        ssh ternakpro.id@ssh.gb.stackcp.com "cd /home/sites/2b/5/535431543a/public_html/ternakpro_app && php artisan migrate --force"

    # Langkah 8: Clear cache untuk aplikasi Laravel
    - name: Clear Laravel cache
      run: |
        ssh ternakpro.id@ssh.gb.stackcp.com "cd /home/sites/2b/5/535431543a/public_html/ternakpro_app"
