name: Deploy TernakPro HTML to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy ke StackCP menggunakan SSH
      - name: Deploy to StackCP
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ssh.gb.stackcp.com
          username: ternakpro.id
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigasi ke direktori deployment
            cd /home/sites/2b/5/535431543a/public_html/ternakpro_html
            
            # Sinkronkan file dari repositori ke server
            # Gunakan rsync untuk efisiensi, salin semua file dari checkout
            rsync -av --delete /home/runner/work/ternak_pro_html/ternak_pro_html/ .
            
            # Atur izin file
            chmod -R 755 .
